<?php

/**
 * See horde/config/prefs.php for documentation on the structure of this file.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE! DO NOT COPY prefs.php TO prefs.local.php!
 * Local overrides ONLY MUST be placed in var/config/folks/prefs.local.php or
 * var/config/folks/prefs.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use var/config/folks/prefs-servername.php.
 */

$prefGroups['Preview'] = [
    'column' => _("Preview"),
    'label' => _("How to preview users"),
    'desc' => _("Set users preview paramaters"),
    'members' => ['sort_by', 'sort_dir', 'per_page'],
];

$prefGroups['Settings'] = [
    'column' => _("Settings"),
    'label' => _("Modify account preferences"),
    'desc' => _("Set account action details"),
    'members' => ['login_notify', 'friends_approval'],
];

$prefGroups['Activities'] = [
    'column' => _("Settings"),
    'label' => _("Activity log"),
    'desc' => _("Set activity preferences"),
    'members' => ['log_user_comments', 'log_account_changes', 'log_scopes', 'log_scope_comments'],
];

$_prefs['sort_by'] = [
    'value' => 'user_uid',
    'locked' => false,
    'type' => 'enum',
    'enum' => ['user_uid' => _("Username")],
    'desc' => _("Sort by"),
];

$_prefs['sort_dir'] = [
    'value' => 1,
    'locked' => false,
    'type' => 'enum',
    'enum' => [0 => _("Descesending"),
        1 => _("Ascesending")],
    'desc' => _("Sort by"),
];

$_prefs['per_page'] = [
    'value' => 20,
    'locked' => false,
    'type' => 'number',
    'desc' => _("Number of users perpage"),
];

$_prefs['login_notify'] = [
    'value' => 1,
    'locked' => false,
    'type' => 'enum',
    'enum' => [0 => _("No"),
        1 => _("Yes")],
    'desc' => _("Notify friends that I loged in"),
];

$_prefs['friends_approval'] = [
    'value' => 1,
    'locked' => false,
    'type' => 'enum',
    'enum' => [0 => _("No"),
        1 => _("Yes")],
    'desc' => _("Require my confirmation if someone would like to add me to his freidn list."),
];

$_prefs['log_user_comments'] = [
    'value' => 1,
    'locked' => false,
    'type' => 'enum',
    'enum' => [0 => _("No"),
        1 => _("Yes")],
    'desc' => _("Log when we comment a user?"),
];

$_prefs['log_account_changes'] = [
    'value' => 1,
    'locked' => false,
    'type' => 'enum',
    'enum' => [0 => _("No"),
        1 => _("Yes")],
    'desc' => _("Log account changes?"),
];

$apps = [];
/*
foreach ($GLOBALS['registry']->listApps() as $app) {
    $apps[$app] = $GLOBALS['registry']->get('name', $app);
}
asort($apps);
*/

$_prefs['log_scopes'] = [
    'value' => 'a:0:{}',
    'locked' => false,
    'type' => 'multienum',
    'enum' => $apps,
    'desc' => _("Application you would like NOT to log your activitiy when you post a new PUBLIC CONTENT."),
];

foreach ($apps as $app) {
    if (!$GLOBALS['registry']->hasMethod('commentCallback', $app)) {
        unset($apps[$app]);
    }
}

$_prefs['log_scope_comments'] = [
    'value' => 'a:0:{}',
    'locked' => false,
    'type' => 'multienum',
    'enum' => $apps,
    'desc' => _("Application you would like NOT to log activitiy when you post a new PUBLIC COMMENT"),
];
